### PR TITLE
Create msPartner

### PR DESCRIPTION
**Pull request by TonyDuong**
@IoT

### CODE REVIEW

**Comment by hansmbakker** [comment]
What is this supposed to do? There is no useful description and the code seems out of place.

Also, looking at your profile it seems like you want to make it seem that you work with a lot of repositories and companies??

**Comment by TonyDuong** [comment]
It is only a variety of fields, related to information technology

**Comment by hansmbakker** [comment]
So why should this be merged? What problem does it solve?

This is the first time i see a pr on GitHub that feels like a troll action.

**Comment by pulcher** [comment]
This seems to be nothing useful and doesn't add to the sample.  It is clearly in the wrong place in the tree structure to be really be useful.  

How would this enum be used in the in the "Hello World" sample?

**Comment by TonyDuong** [comment]
This is just a sample code, and does not mean troll or anything else, a code for reference and need comments

**Comment by saraclay** [comment]
Sorry, going to have to close this PR as I'm in agreement with @hansmbakker and @pulcher

**Pull request closed without merging**
