### PR TITLE
Add RPi Cognitive Service

### PR DESCRIPTION
**Pull request by shijiong**
Add RPi Cognitive Service from https://www.hackster.io/JiongShi/microsoft-cognitive-services-demo-on-windows-10-iot-core-4d846e

### CODE REVIEW

**Comment by saraclay** [comment]
Hi @shijiong, a few things...
-There are comments that are written in Chinese. Could you potentially translate those? Also, the file names say "RPiCognitiveServie" instead of "RPiCognitiveService". It is probably some work, but could you fix that typo? Lastly, could you follow the format of the other samples? Thank you.

**Comment by shijiong** [comment]
Hello, @saraclay Sara
I've re-build my project, modify the Chinese comments to English. And change the Readme.md file. Would you please take a look at this version? Thanks.

**Comment by derekameer** [comment]
Hey @shijiong, 

Looks like the Emotion API is going to be deprecated: https://azure.microsoft.com/en-us/services/cognitive-services/emotion/

Can you please adjust your sample to use the Face API instead? That should be all we need to merge the PR.

Thanks!

**Comment by shijiong** [comment]
Hello, @derekameer 
That may take a few days for me to achieve this. I will let you know as soon as i finished.

**Comment by shijiong** [comment]
Hello, @saraclay and @derekameer 
I've upgraded the version of Face API to the latest, deleted the Emotion API reference, and modified the project files. Would you please take a look at this version? 
Thanks!

**Pull request merged**
