### PR TITLE
HC-SR04 Ultrasonic sensor sample

### PR DESCRIPTION
**Pull request by oh6hay**
Simple app to measure distance using the HC-SR04 ultrasonic sensor with GPIO.

### CODE REVIEW

**Comment by saraclay** [comment]
Hi @oh6hay, thank you so much for this submission! Would you be at all interested in using GpioChangeReader instead of stopwatch?

**Comment by oh6hay** [comment]
sure, why not, if it makes more sense. I'll see if the timing on it is as accurate as with the stopwatch. I'll get back on this this weekend.

**Comment by oh6hay** [comment]
the GpioChangeReader docs indeed suggests it's better suited to measure the time between the edges. The stopwatch is still useful for timing the trigger pulse.

**Comment by saraclay** [comment]
You are fantastic, @oh6hay! Thank you for your contribution!

**Pull request merged**
