### PR TITLE
Fix build break in custom vision brought by common logging

### PR DESCRIPTION
**Pull request by jcoliz**
@seanmcd-msft sorry, I broke custom vision sample with the common logger change. This fixes. Pls verify that I understood your intent with the affected line.

### CODE REVIEW

**Comment by seanmcd-msft** [comment]
Yes, this change is correct.  Sorry, I was thinking in the back of my head there was a reason I had them public while reviewing you other change yesterday and then I got interrupted and forgot to follow up before approving the change.

**Comment by jcoliz** [comment]
Thanks for review, and sorry for so many other things getting into this PR. I didn't realize if you update a branch after submitting a PR, it brings in the later changes too. Other changes are just cleanups of serial sample, and using common logger.

**Comment by jcoliz** [comment]
@saraclay, ready to go.

**Comment by seanmcd-msft** [comment]
Yeah, I agree that not being able to control whether subsequent commits go into the PR or not is annoying. You have to wait for the PR to go through or work in a separate branch until the PR goes through.

**Comment by saraclay** [comment]
@jcoliz sorry! not sure why I'm not getting notifications... feel free to just ping me next time as soon as it's ready.

**Pull request merged**
